### ISSUE TITLE
windows10下debug报错

### ISSUE THREAD

**Issue by roger-zhao** [itisyang/playerdemo#10]
编译debug环境：VS2017，QT5.9.6，win10 x64
报错：
ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread. Current thread 26ff4538. Receiver ‘PlayorPauseBtn' was created in thread 0x……"
请教如何解决？

**Comment by itisyang** [comment]
这个问题时，线程事件投递问题，理论上来说，应该不会报错才对，我一般直接使用release编译调试，你可以试一下

**Comment by roger-zhao** [comment]
@itisyang 感谢回复，我试过了，好像还有，不过点击ignore倒也不影响使用。VS+QT刚开始入坑，请问有推荐的入门博客或者资料没，多谢！

**Comment by itisyang** [comment]
Qt 的文档就是最好的资料

**Comment by roger-zhao** [comment]
@itisyang 收到！再请教个问题，用这个播放器放高码率的rtsp流，延迟比VLC要大好多（1s以上），如果要做调优的话应该如何做呢？是调整datactl.h里面的一些比如MAX_QUEUE_SIZE，SAMPLE_ARRAY_SIZE，#define VIDEO_PICTURE_QUEUE_SIZE 3
#define SUBPICTURE_QUEUE_SIZE 16
#define SAMPLE_QUEUE_SIZE 9
#define FRAME_QUEUE_SIZE FFMAX(SAMPLE_QUEUE_SIZE, FFMAX(VIDEO_PICTURE_QUEUE_SIZE, SUBPICTURE_QUEUE_SIZE)) 之类的，还是必须得对ffmpeg的编码调用做优化？视频小白一个，还请多指教，感谢！

**Comment by roger-zhao** [comment]
@itisyang 网上看到有 “-fflags nobuffer -flags low_delay -framedrop -strict experimental”，用ffplay试了下，看起来能把rtsp的延迟降低到.5s左右。还在尝试

**Comment by itisyang** [comment]
延时问题，需要慢慢调
