### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by funny1624** [itisyang/playerdemo#11]
在VS下使用最新提交的代码版本编译出现大量错误，基本上都是提示重定义及缺少标识符的错误。编译0.1.0不会报错
比如说：
1>e:\free\potplayer\playerdemo\datactl.h(199): error C2146: 语法错误: 缺少“;”(在标识符“sampq”的前面)
1>e:\free\potplayer\playerdemo\datactl.h(216): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>e:\free\potplayer\playerdemo\datactl.h(216): error C2086: “int PacketQueue”: 重定义

**Comment by funny1624** [comment]
@itisyang 大神的代码质量还是挺不错的，看起来很舒服，赞一个。有个问题，我用公司电脑跑这个demo的时候，播放器没有声音，用其它播放器有声音。把这个demo拿到自己笔记本上放的时候又是有声音的。用ffplay播放的时候也是没有声音，不知道是ffplay代码那块哪里没有初始化好，会提示以下信息：SDL_OpenAudio (2 channels, 48000 Hz): WASAPI can't initialize audio client:
SDL_OpenAudio (1 channels, 48000 Hz): WASAPI can't initialize audio client:
No more combinations to try, audio open failed

**Comment by itisyang** [comment]
大概率驱动没装，或者扬声器坏的

**Comment by funny1624** [comment]
@itisyang 已查明问题， 在audio_open入口处加上CoInitialize(NULL);可解决在windows上部分情况无声的问题

**Comment by lidedongsn** [comment]
set SDL_AUDIODRIVER=directsound
