### ISSUE TITLE
编译通过，运行时 提示“程序异常结束”

### ISSUE THREAD

**Issue by GenaWang** [itisyang/playerdemo#16]
你好，安装了Qt编译通过，运行时提示“程序异常结束”。
错误：
Clang Code Model: Error: The clangbackend executable "C:\Qt5.12.0\Tools\QtCreator\bin\clangbackend.exe" could not be started (timeout after 10000ms)

**Comment by itisyang** [comment]
依赖库不全

**Comment by Eversee22** [comment]
你可能需要将包含的头文件换成你使用的版本
