### ISSUE TITLE
建议：全屏播放增加进度条显示

### ISSUE THREAD

**Issue by geekyouth** [itisyang/playerdemo#2]
建议：全屏播放增加进度条显示

测试过不下100个皮肤，
目前没找到支持全屏进度条的皮肤。

**Comment by itisyang** [comment]
好，加入下一步计划

**Comment by itisyang** [comment]
> 建议：全屏播放增加进度条显示
> 
> 测试过不下100个皮肤，
> 目前没找到支持全屏进度条的皮肤。

你好，现代码库中已增加全屏进度条显示，至于更换皮肤功能，有待开发。
谢谢反馈！
