### ISSUE TITLE
播放器的工作原理

### ISSUE THREAD

**Issue by xbliuHNU** [itisyang/playerdemo#23]
你好，我的需求是做一个简化版的视频播放器，能够做到逐帧的播放控制，因为没有这方面的预备知识，如ffmpeg解码和SDL渲染，看了你提供的代码后无从下手做一些更改，因此想请教一下这其中的大致原理，模块之间如何工作，需要用到哪些API？方便的话，可以提供一些上手资料，先谢谢了

**Comment by itisyang** [comment]
@xbliuHNU 直接官网看文档就行

**Comment by xbliuHNU** [comment]
@itisyang 好的，谢谢
