### ISSUE TITLE
Ubuntu下QT5编译失败

### ISSUE THREAD

**Issue by yfBong** [itisyang/playerdemo#25]
你好，首先十分感谢你的这个demo给我们提供了新人练手学习的机会！
我在Ubuntu QT5的编译环境下编译失败，对应编译失败的文件都是videoctl.cpp，似乎都是语法问题，
![微信图片_20200225083949](https://user-images.githubusercontent.com/51224366/75203910-69d75d00-57aa-11ea-98ff-47851e8ff0b6.png)
这是怎么回事呢？谢谢

**Comment by itisyang** [comment]
看报错信息大概是ffmpeg版本不对，可能是太新了，有些成员找不到了

**Comment by yfBong** [comment]
感谢
