### ISSUE TITLE
放在哪个bin目录下啊？playerdemo-master\lib\ffmpeg\bin吗？

### ISSUE THREAD

**Issue by david-guoguo** [itisyang/playerdemo#27]
![image](https://user-images.githubusercontent.com/40413210/96427316-f8fd1d80-1230-11eb-8eb2-746eed63a301.png)

**Comment by david-guoguo** [comment]
可以给出ffmpeg的链接吗？
这个  FFmpeg 库下载地址 https://ffmpeg.zeranoe.com/builds/  已经失效了
自己下载了几个版本都不行的  >_<

**Comment by itisyang** [comment]
exe生成目录下，ffmepg随便下载一个64位的就行，http://ffmpeg.org/ 去下载
