### ISSUE TITLE
linux版打包

### ISSUE THREAD

**Issue by doufumantou** [itisyang/playerdemo#3]
建议对linux版先提供AppImage或者deb包,  毕竟会编译的大佬不多

**Comment by itisyang** [comment]
很好的建议，下版本提供

**Comment by NingerJohn** [comment]
> 很好的建议，下版本提供

库主，至少先提供一下linux下面编译的教程。非常感谢。win下面一直用的potplayer。非常好用。开发的时候，会用ubuntu，一直没找到非常棒的播放器。所以很想试试。但是对C++和Qt编译不懂。

**Comment by itisyang** [comment]
> > 很好的建议，下版本提供
> 
> 库主，至少先提供一下linux下面编译的教程。非常感谢。win下面一直用的potplayer。非常好用。开发的时候，会用ubuntu，一直没找到非常棒的播放器。所以很想试试。但是对C++和Qt编译不懂。

好，国庆期间一定给出Linux版本，及编译教材

**Comment by itisyang** [comment]
已增加 Linux 编译说明，暂时没有打包，在下一个release将给出包。谢谢。
