### ISSUE TITLE
ubuntu编译时，在ui_ctrlbar.h下找不到CustomSlider.h

### ISSUE THREAD

**Issue by ruokaic** [itisyang/playerdemo#31]
需要将找不到的头文件拷贝到debug目录下才能成功运行，请问是什么原因呢？希望能解答一下，感谢~

**Comment by itisyang** [comment]
编译的顺序不对，可能是中途改了文件，只进行了部分编译，试试清理后，重新编译

**Comment by ruokaic** [comment]
非常感谢

**Comment by 0X-Angel** [comment]
我在ubuntu20下编译遇到这个问题了。
请在.pro文件里面找到这三段：
INCLUDEPATH += src \
    lib/sdl/include \
    lib/ffmpeg/include
把它从花括号里提取到外面（或者复制到外面）就好了
原因是它被包到了win32判断条件内，提取出来就好了
