### ISSUE TITLE
Mac端编译运行后播放窗口是透明的，导入视频就闪退

### ISSUE THREAD

**Issue by GreatBastard** [itisyang/playerdemo#35]
![截屏2022-01-22 下午1 49 09](https://user-images.githubusercontent.com/74351537/150626652-87665b9e-16d3-4070-82e4-dd550ee0295c.png)

通过homebrew安装的最新版ffmpeg和sdl2
求大佬帮忙解决一下问题～

**Comment by GreatBastard729** [comment]
编译完了还会产生这些warning
![截屏2022-01-22 下午1 54 00](https://user-images.githubusercontent.com/74351537/150626848-65da11bc-70b6-4ac6-8b6f-b07fc12a9151.png)

是不是需要修改一下sdk版本呢？求大佬指点

**Comment by itisyang** [comment]
> 

11.0是macOS版本吗？
这个问题大概率是sdl渲染坐标问题，我在ubuntu下遇到过（0,0）不是在左上角，导致渲染图像在界面之外

**Comment by itisyang** [comment]
> 

11.0是macOS版本吗？
这个问题大概率是sdl渲染坐标问题，我在ubuntu下遇到过（0,0）不是在左上角，导致渲染图像在界面之外

**Comment by GreatBastard** [comment]
那具体需要在哪个文件修改渲染坐标呢？不太清楚诶，希望大佬能详细解答，感激不尽(⁎⁍̴̛ᴗ⁍̴̛⁎)

**Comment by GreatBastard** [comment]
大佬可以留个联系方式嘛？我想有偿请您帮我解决这个问题，感激不尽！
