### ISSUE TITLE
播放视频没有声音，全屏后再还原画面还是全屏大小

### ISSUE THREAD

**Issue by igofreely** [itisyang/playerdemo#4]
发现以下bug：
播放视频没有声音
全屏后再还原画面还是全屏大小
编译后先播放一个视频，然后换另一播放或点击播放列表报错

**Comment by itisyang** [comment]
> 发现以下bug：
> 播放视频没有声音
> 全屏后再还原画面还是全屏大小
> 编译后先播放一个视频，然后换另一播放或点击播放列表报错

请问是用的什么编译器，并且检查FFmpeg、SDL2静态库动态库头文件版本是否一致（版本、位数）。
如果还是存在异常，请提供报错信息、编译信息、打印日志
