### ISSUE TITLE
QT启动项目失败

### ISSUE THREAD

**Issue by V-lambow** [itisyang/playerdemo#53]
平台win11
编译器msvc2017
qt5.14.2
编译没有任何问题，但是一点启动就
![image](https://github.com/user-attachments/assets/51842f44-bce7-4877-af78-03e1796ee973)

**Comment by V-lambow** [comment]
缺少dll而已，居然不报出来

**Comment by V-lambow** [comment]
只要把ffmpeg相关的dll放进去就好了

**Comment by id4su** [comment]
你好 我也是这个问题 方便解答一下吗 我把dll放进来还是不行

![Image](https://github.com/user-attachments/assets/1f2b59d3-d128-48a8-adb1-432d9411abc9)
