### ISSUE TITLE
.pro 文件有语法错误

### ISSUE THREAD

**Issue by X1aomu** [itisyang/playerdemo#6]
其中一空白行导致 Qt Creator 解析文件失败：
https://github.com/itisyang/playerdemo/blob/c3154f19f4f391c28ca9c1c87e2b7a7a23a9af16/playerdemo/playerdemo.pro#L15-L26
18 行这一行留空即代表 LIBS 这一行结束，后面的 19-26 行组成新的一行了。

**Comment by itisyang** [comment]
> 其中一空白行导致 Qt Creator 解析文件失败：
> [playerdemo/playerdemo/playerdemo.pro](https://github.com/itisyang/playerdemo/blob/c3154f19f4f391c28ca9c1c87e2b7a7a23a9af16/playerdemo/playerdemo.pro#L15-L26)
> 
> Lines 15 to 26 in [c3154f1](/itisyang/playerdemo/commit/c3154f19f4f391c28ca9c1c87e2b7a7a23a9af16)
> 
>  LIBS += -L$$PWD/lib/sdl/lib \ 
>      -L$$PWD/lib/ffmpeg/lib \ 
>      -lSDL2 \ 
>   
>      -lavcodec \ 
>      -lavdevice \ 
>      -lavfilter \ 
>      -lavformat \ 
>      -lavutil \ 
>      #-lpostproc \ 
>      -lswresample \ 
>      -lswscale 
> 
> 18 行这一行留空即代表 LIBS 这一行结束，后面的 19-26 行组成新的一行了。

已修复

**Comment by X1aomu** [comment]
Fixed by https://github.com/itisyang/playerdemo/commit/260c11ec861ffb7ab220cf6e405a73302d9d8ff2
