### ISSUE TITLE
linux下编译出现错误

### ISSUE THREAD

**Issue by royaalto** [itisyang/playerdemo#7]
在pro里+ QMAKE_CXXFLAGS += -std=c++11
`/home/roy/delete/Media-player/playerdemo/playerdemo/videoctl.cpp:2039: error: no matching function for call to ‘VideoCtl::connect(VideoCtl*, void (VideoCtl::*)(), void (VideoCtl::*)())’
     connect(this, &VideoCtl::SigStop, &VideoCtl::OnStop);
                                                        ^`

**Comment by royaalto** [comment]
是ｑｔ版本问题吗？

**Comment by royaalto** [comment]
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
I try to install 5.9.7 however still can not compile through,
what is your environment?
sorry my Chinese input collapsed

**Comment by itisyang** [comment]
我是在ubuntu1804下，Qt 5.9.6 (GCC 5.3.1, 64bit)，直接用QtCreator打开编译的
编译之前你要先安装 FFmpeg 和 SDL2-dev，具体的你可以参考项目的 readme.md
你的报错信息里 connect编译不过，应该是老版本Qt不支持我这种写法，我用的connect方式比较新

**Comment by royaalto** [comment]
我现在用改为了5.9.7但是还是这个｀/home/roy/delete/Media-player/playerdemo/playerdemo/videoctl.cpp:2039: error: no matching function for call to ‘VideoCtl::connect(VideoCtl*, void (VideoCtl::*)(), void (VideoCtl::*)())’
     connect(this, &VideoCtl::SigStop, &VideoCtl::OnStop);
                                                        ^｀方程报错，能不能改为另外一个种方式，我ｑｔ不是很是懂

**Comment by itisyang** [comment]
我重新编译了下，ubuntu 和 Windows 均无编译报错。
如果你实在编译不过，可以尝试 connect(this, &VideoCtl::SigStop, this, &VideoCtl::OnStop);
